### ISSUE TITLE
error

### ISSUE THREAD

**Issue by nitinrajg** [dev-rvk/so_decompiler#1]
I'm unable to use docker
I'm using the repo in vscode

**Comment by dev-rvk** [comment]
Hi,
Please mention your issue in detail
Refer: [Writing Good GitHub Issues](https://github.com/codeforamerica/howto/blob/master/Good-GitHub-Issues.md)

**Comment by nitinrajg** [comment]
docker pull devrvk/so-decompiler:latest
'docker' is not recognized as an internal or external command,
operable program or batch file.

plz check this

**Comment by dev-rvk** [comment]
The README assumes that docker is installed on your system.
Refer: [https://docs.docker.com/](https://docs.docker.com/)
